# Generated by Django 3.1.3 on 2020-11-14 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_articulos_clientes_pedidos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulos',
            old_name='email',
            new_name='precio',
        ),
    ]
